[package]
name = "c2pa-python"
version = "0.5.0"
edition = "2021"
authors = ["Gavin Peacock <gpeacock@adobe.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "c2pa"
crate-type = ["staticlib"]

[dependencies]
c2pa = { git = "https://git.aquareum.tv/aquareum-tv/c2pa-rs.git", rev = "ac3a37eb1f51b9498b6b2974bd26ed2a362bf517", features = [
  "unstable_api",
  "openssl",
] }
# c2pa = { path = "../c2pa-rs/sdk", features = ["unstable_api", "openssl"] }
pem = "3.0.3"
serde = { version = "1.0.197", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "1.0.49"
uniffi = "= 0.25.0"

[build-dependencies]
uniffi = { version = "= 0.25.0", features = ["build"] }
